project:
  type: website
  output-dir: docs

website:
  title: "Zane's DBSFW Solutions"
  navbar:
    right:
      - icon: house-door-fill
        href: https://wzbillings.com
      - icon: github
        href: https://github.com/wzbillings
      - icon: mastodon
        href: https://fediscience.org/@wzbillings
format:
  html:
    theme:
      dark: vapor
      light: pulse
    css: styles.css



