project:
  type: website
  output-dir: docs

website:
  title: "Book Solutions and Notes"
  navbar:
    right:
      - icon: house-door-fill
        href: https://wzbillings.com
      - icon: github
        href: https://github.com/wzbillings/DBSFW
      - icon: mastodon
        href: https://fediscience.org/@wzbillings
format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css



